language: node_js
notifications:
  email: false
before_script:
  - npm prune

# Define the default stage
stage: 📋 Test

jobs:
  include:
    # Publish step
    # Only runs on master branch and only once
    - stage: 🚀 Publish
      script: npm run semantic-release
      if: branch = master AND type != pull_request

# Define the order of stages
stages:
  - 📋 Test
  - 🚀 Publish
